from setuptools import setup, find_packages

setup(
    name="lm-api",
    description="REST API for Managing the Links between OSLC Applications",
    version="1.0.0",
    author="Koneksys",
    author_email="axel.reichwein@koneksys.com",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "uwsgi",
        "python-dotenv",
        "SQLAlchemy",
        "werkzeug",
        "flask",
        "flask-restx",
        "flask-sqlalchemy",
        "flask-migrate",
        "flask-cors",
        "flask-httpauth",
        "flask-mail",
        "python-keycloak",
        "python-logging-loki",
        "py2neo",
        "sentry-sdk[flask]",
        "psycopg2-binary",
        "mixpanel",
        "requests",
        "rdflib",
    ],
    extras_require={
        "dev": [
            "black",
            "flake8<5",
            "pre-commit",
            "pydocstyle",
            "pytest",
            "pytest-black",
            "pytest-clarity",
            "pytest-dotenv",
            "pytest-flake8",
            "pytest-flask",
            "tox",
        ],
        "test": ["coverage"],
    },
)
